[package]
name = "bitmaps"
version = "3.2.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
edition = "2021"
license = "MPL-2.0+"
description = "Fixed size boolean arrays"
repository = "https://github.com/bodil/bitmaps"
documentation = "http://docs.rs/bitmaps"
readme = "./README.md"
categories = ["data-structures"]
exclude = ["release.toml", "proptest-regressions/**"]

[features]
default = ["std"]
std = []

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.4.0"
